### ISSUE TITLE
链接 - 夏沫花火zzz🌙 (Muska_Ami)のLife

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/muska-ami-blog#13]
https://blog.1l1.icu/links/ 

 欢迎添加本站友链，申请格式及本站信息如下：  名称：夏沫花火zzz🌙 (Muska_Ami)のLife 链接：https://blog.1l1.icu 介绍：Keep doing,keep loving. 头像：https://pan.1l1.icu/f/LG4Te/%E5%A4%B4%E5%83%8F.03.jpeg   要求：  支持HTTPS 支持TLS v1.3 使用受广泛信任的证书 无

**Comment by ltzXiaoYanMo** [comment]
:thinking:

**Comment by Muska-Ami** [comment]
> @ltzXiaoYanMo
> :thinking:

🥺

**Comment by ltzXiaoYanMo** [comment]
> @Muska-Ami
> > @ltzXiaoYanMo
> > :thinking:
> 
> 🥺

~~Markdown 语法忘的差不多了~~

😭

**Comment by ltzXiaoYanMo** [comment]
:thinking:

**Comment by NiuBoss123** [comment]
名称：御坂秋生の小站
链接：https://www.akio.top
介绍：不努力就只能听到别人的好消息
头像：https://server.akio.top/icon

**Comment by Muska-Ami** [comment]
> @NiuBoss123
> 名称：御坂秋生の小站
> 链接：https://www.akio.top
> 介绍：不努力就只能听到别人的好消息
> 头像：https://server.akio.top/icon

加上啦~

**Comment by ltzXiaoYanMo** [comment]
> > @NiuBoss123
> > 名称：御坂秋生の小站
> > 链接：https://www.akio.top
> > 介绍：不努力就只能听到别人的好消息
> > 头像：https://server.akio.top/icon
> 
> 加上啦~

草拟吗加我的就得好几天是罢（

**Comment by Muska-Ami** [comment]
> @ltzXiaoYanMo
> > > @NiuBoss123
> > > 名称：御坂秋生の小站
> > > 链接：https://www.akio.top
> > > 介绍：不努力就只能听到别人的好消息
> > > 头像：https://server.akio.top/icon
> > 
> > 加上啦~
> 
> 草拟吗加我的就得好几天是罢（

谁允许你说话了（
