### ISSUE TITLE
Vuex 导出踩坑 - 夏沫花火zzz🌙 (Muska_Ami)のLife

### ISSUE THREAD

**Issue by Muska-Ami** [Muska-Ami/muska-ami-blog#8]
https://blog.1l1.icu/2023/09/28/vuex-dao-chu-cai-keng/ 

 Keep doing, keep loving❤.

**Comment by shiftz300** [comment]
草，所以你ide不提示吗

**Comment by Muska-Ami** [comment]
> 草，所以你ide不提示吗

他没提示的说(
